baseURL = "https://kmgk.github.io/introduction-of-information-processing/"
languageCode = "en-us"
title = "情報処理概論演習"
theme ="hugo-theme-basic"
enableEmoji = true 

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  titleEmoji = ":tada:"
  # change this!
  twitter = "siegerts"

[Permalinks]
  post = "post/:slug"

[[params.menu]]
  name = "記事一覧"
  url = "post/"


  